# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_reporting', '0002_wlanusage_mtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wlanusage',
            name='mDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
