# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_reporting', '0003_auto_20161202_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDHEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mInterface', models.CharField(default='unknown', max_length=10)),
                ('mTemperature', models.FloatField(default=0.0)),
                ('mHumidity', models.FloatField(default=0.0)),
                ('mDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
