# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_reporting', '0005_auto_20170607_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordhentry',
            name='mTimezone',
            field=models.CharField(default='America/Argentina/Buenos_Aires', max_length=200),
            preserve_default=False,
        ),
    ]
