# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-08 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_reporting', '0007_auto_20170607_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDHEntryComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mTemperatureAv', models.FloatField(default=0.0)),
                ('mHumidityAv', models.FloatField(default=0.0)),
                ('mHour', models.IntegerField(default=-1)),
            ],
        ),
    ]
