# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_reporting', '0008_sensordhentrycomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordhentrycomp',
            name='mHour',
            field=models.FloatField(default=-1.0),
        ),
    ]
