# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-18 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_reporting', '0009_auto_20170609_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorDHEntryComp',
        ),
    ]
